[workspace]
members = ["programs/paywall"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
overflow-checks = true

[workspace.dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"